### ISSUE TITLE
npm run setup fails

### ISSUE THREAD

**Issue by rfossella** [wurde/themebuilder#2]
Hello,
Running Windows 10 w/ node **v6.11.2** and npm **v3.10.10**.   When I execute _npm run setup_ I get the following:
```
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "setup"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! themebuilder@0.1.0 setup: `npm install | npm run clone-bootstrap && npm run init-custom`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the themebuilder@0.1.0 setup script 'npm install | npm run clone-bootstrap && npm run init-custom'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the themebuilder package,
npm ERR! not with npm itself.
```
Is there a minimum requirement for running the install and the app?

Thanks.
Rob

**Comment by wurde** [comment]
I'm running node **v8.6.0**, so maybe that's the problem. But I also haven't touched Windows in a decade. If you solve it and open a pull request then I'll merge the fix.

**Comment by wurde** [comment]
I've increased permissiveness of Node engines to be >=8. The specific error is likely a problem with how Windows builds file paths.

**Comment by rfossella** [comment]
OK, thanks.  I actually thought this would be bit more plug and play across any OS since we are a Windows shop.  If I get anywhere w/Window path I'll be sure to post.

**Comment by wurde** [comment]
Ok, best of luck. Also Windows 10 now offers the ability to run Ubuntu(Linux) via the Windows Store? 

Also I know there is a toolchain for publishing binaries of your Electron app for Windows, but I'm not a fan of black-boxing code. If you look at `index.js` you'll see I only use Electron as a thin wrapper around an Express web app. This architecture allows for easily portable of code between desktop and web applications.
