### ISSUE TITLE
Setup script throws errors on Windows

### ISSUE THREAD

**Issue by mevanloon** [wurde/themebuilder#3]
Because the setup script doesn't check what environment it runs on, it doesn't function on Windows.

**Comment by wurde** [comment]
What error are you receiving?

**Comment by Thorgrim901** [comment]
Same for me. The error is that "rm", "touch", "grep", "sed" are not commands in windows.

**Comment by wurde** [comment]
Ok. I'll accept a pull request replacing those commands with nodejs equivalents.
